apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic
  labels:
    app: dynamic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic
  template:
    metadata:
      labels:
        app: dynamic
    spec:
      containers:
      - image: gcr.io/whim-nks/github.com/netapp/hci-nks-demo/dynamic:d73df1b
        imagePullPolicy: Always
        name: dynamic-demo
        ports:
        - containerPort: 8080
        env:
        - name: PRESENTER
          value: Add your name
        - name: ENVIRONMENT
          value: Google Cloud Platform
        - name: STATIC
          value: http://34.83.30.56
